---
galaxy_info:
  role_name: docker
  author: Frederico Araujo and Teryl Taylor
  description: SysFlow telemetry stack installation/uninstallation.
  company: IBM Research
  license: MIT
  min_ansible_version: 2.4

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
    - name: Debian
      versions:
        - stretch
        - buster
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - sysflow
    - docker
    - containerization
    - system
    - os
dependencies:
  # ansible-galaxy install darkwizard242.docker
  - role: darkwizard242.docker
    #vars:
    #  docker_group_desired_state: absent
    #  docker_user_desired_state: absent
    when: sysflow_install_docker
